### ISSUE TITLE
Error while run src/SvxLinkWrapper.py

### ISSUE THREAD

**Issue by tamilnaduhams** [guysoft/SvxLinkWrapper#1]
Hi,
am receiving an error while run svxlinkwrapper.py i tested in both python 2.7 and python 3.4
error file screen shot attached.

![error](https://cloud.githubusercontent.com/assets/23480119/20310860/8bdcf41e-ab73-11e6-9d76-0c5984889459.png)

**Comment by guysoft** [comment]
Ok, what is in your `config.ini` in `SVXLINK_CMD`?
And what is the output of  `ls -l /usr/bin/svxlink` (or what ever is in SVXLINK_CMD)?

**Comment by tamilnaduhams** [comment]
## config.ini

SVXLINK_CMD=/usr/local/share/svxlink

pi@rpi3-echolink:~$ ls -l /usr/local/share/svxlink
total 20
drwxr-sr-x 2 root staff 4096 Nov 12 21:56 events.d
-rw-r--r-- 1 root staff 4209 Dec 19  2015 events.tcl
drwxr-sr-x 2 root staff 4096 Nov 12 21:56 modules.d
drwxr-xr-x 3 root staff 4096 Nov 12 22:20 sounds

**Comment by tamilnaduhams** [comment]
My Svxlink location
--------------------
/usr/local/etc/svxlink/svxlink.conf
/usr/local/etc/svxlink/svxlink.d/ModuleEchoLink.conf

My SvxLinkWrapper location
---------------------------------
/home/pi/SvxLinkWrapper

**Comment by tamilnaduhams** [comment]
hey lastly i found the solution with reference to your comment.
i changed **SVXLINK_CMD=/usr/local/share/svxlink**  to **SVXLINK_CMD=/usr/local/bin/svxlink**
now it is working.

**Comment by guysoft** [comment]
Indeed, `SVXLINK_CMD` Needs to point to the command, the reason you got ``permission denied` errors was because it was trying to execute a folder, and not a binary.
